package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, 14 November, 2017 7:28:53 PM IST
*/

public interface HelloOperations 
{
  String sayhello ();
  void shutdown ();
} // interface HelloOperations
